from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib.units import cm
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
import io
import textwrap

def generate_report_pdf(analysis: dict, mode: str) -> io.BytesIO:
    """
    Generates a PDF report from the analysis data.
    Returns a BytesIO object containing the PDF.
    """
    buffer = io.BytesIO()
    c = canvas.Canvas(buffer, pagesize=A4)
    width, height = A4
    
    # Header
    c.setFont("Helvetica-Bold", 16)
    c.drawString(2*cm, height - 2*cm, f"FIELD READER REPORT: {mode.upper()}")
    
    c.setFont("Helvetica", 10)
    c.drawString(2*cm, height - 2.8*cm, "Generated by Field Reader AI | Confidential")
    
    c.setLineWidth(1)
    c.line(2*cm, height - 3*cm, width - 2*cm, height - 3*cm)
    
    y = height - 4*cm
    
    # Content Logic
    sections = [
        ("RISK / BEHAVIOR", analysis.get("behavior", "-")),
        ("ROLE / ASYMMETRY", analysis.get("imposed_role", "-")),
        ("HIDDEN MOTIVATION / BLIND SPOT", analysis.get("hidden_motivation", "-")),
        ("FEAR / ECONOMICS", analysis.get("fear", "-")),
        ("VERDICT / RECOMMENDATION", analysis.get("recommendation", "-"))
    ]
    
    for title, content in sections:
        # Title
        c.setFont("Helvetica-Bold", 12)
        c.drawString(2*cm, y, title)
        y -= 0.8*cm
        
        # Content (Wrapped)
        c.setFont("Helvetica", 10)
        wrapper = textwrap.TextWrapper(width=80)
        lines = wrapper.wrap(text=content)
        
        for line in lines:
            c.drawString(2*cm, y, line)
            y -= 0.5*cm
        
        y -= 0.5*cm # Extra space between sections
        
        if y < 3*cm: # New page if low
            c.showPage()
            y = height - 2*cm

    # Footer
    c.setFont("Helvetica-Oblique", 8)
    c.drawString(width/2 - 2*cm, 1*cm, "Field Reader B2B Intelligence")
    
    c.save()
    buffer.seek(0)
    return buffer
